### ISSUE TITLE
pm2 start on public Error

### ISSUE THREAD

**Issue by kaminono** [ipfs-labs/ipfs-pubsub-room-demo#2]
```
TypeError: hex is not a function
    at Function.from (native)
    at Function.from (native)
    at Object.<anonymous> (/root/ipfs-pubsub-room-demo/node_modules/ethereumjs-block/node_modules/ethereumjs-util/index.js:31:28)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/root/ipfs-pubsub-room-demo/node_modules/ethereumjs-block/header.js:1:77)
```

**Comment by jacobandresen** [comment]
which node version are you running?

**Comment by kaminono** [comment]
sorry,The problem is solved。
And then have a new question that has been submitted to https://github.com/ipfs/js-ipfs/issues/963
